@app.route("/sync", methods=["GET"])
def manual_sync():
    try:
        from sync_drive_to_gsheet import upload_to_google_sheet, download_latest_schedule

        # 上傳最新 Excel 到 Google Sheets
        upload_to_google_sheet(download_latest_schedule())

        # ✅ 清除舊快取，讓系統強制重新讀取
        load_schedule.cache_clear()

        return "✅ 課表同步成功", 200
    except Exception as e:
        return f"❌ 同步失敗：{str(e)}", 500
