name: Daily Schedule Sync to Render

on:
  schedule:
    - cron: "0 22 * * *"  # 每天早上 6 點（台灣時間）
  workflow_dispatch:

jobs:
  call-sync-endpoint:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger /sync endpoint
        run: |
          curl -L https://my-schedule-ne7a.onrender.com/sync
