name: Daily Schedule Sync to Render

on:
  schedule:
    # 台灣時間 06:00；UTC+0 為 22:00
    - cron: "0 22 * * *"
  workflow_dispatch:

jobs:
  call-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Call /sync endpoint
        run: |
          curl -L https://my-schedule-ne7a.onrender.com/sync
